[package]
name = "atsamd-demo"
version = "0.1.0"
authors = ["Henrik Tjäder <henrik@grepit.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
#heapless = "0.6.0"
#embedded-hal = "0.2.4"
#nb = "~0.1"
cortex-m = "0.6.2"
cortex-m-rtic = "0.6.0-alpha.2"
#cortex-m-semihosting = "0.3.5"
#panic-semihosting = "0.5.3"
#paste = "0.1.18"
#typenum = "1.12.0"

[dependencies.atsamd-hal]
#git = "https://github.com/bradleyharden/atsamd.git"
#branch = "clock_rebase"
path = "../atsamd-bradley/hal/"
version = "0.12.0"
features = ["same51n-rt", "unproven"]

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = true
