[package]
name = "atsamd-demo"
version = "0.1.0"
authors = ["Henrik Tjäder <henrik@grepit.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.2"
cortex-m-rtic = "0.6.0-alpha.2"
eeprom24x = "0.4.0"

[dependencies.atsamd-hal]
git = "https://github.com/vccggorski/atsamd.git"
branch = "work/i2c-timeout"
version = "0.12.0"
features = ["same51n-rt", "unproven"]

[profile.dev]
opt-level = 0

[profile.release]
debug = true
lto = true
