[package]
name = "atsamd-demo"
version = "0.1.0"
authors = ["Henrik Tjäder <henrik@grepit.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
cortex-m = "0.6.2"
cortex-m-rtic = "0.6.0-rc.2"

[dependencies.atsamd-hal]
#git = "https://github.com/bradleyharden/atsamd.git"
#branch = "clock_rebase"
path = "../atsamd-bradley/hal/"
version = "0.13.0"
features = ["same51n-rt", "unproven"]

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = true
