MEMORY
{
  FLASH : ORIGIN = 0x400000, LENGTH = 512K
  /* FLASH_UPDATE : ORIGIN = ORIGIN(FLASH)+LENGTH(FLASH), LENGTH = 512K */
  RAM : ORIGIN = 0x20400000, LENGTH = 256K
}

/* SECTIONS { */
/*   __flash_update_start = ORIGIN(FLASH_UPDATE); */
/*   __flash_update_len = LENGTH(FLASH_UPDATE); */
/* } */
